# Generated by Django 4.2 on 2024-03-27 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_coinmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinmodel',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.usermodel'),
        ),
    ]
