# Generated by Django 4.2 on 2024-03-27 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_coinmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinmodel',
            old_name='user',
            new_name='customer',
        ),
    ]
