# Generated by Django 4.2 on 2024-03-27 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_user_coinmodel_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='coin_status',
            field=models.BooleanField(default=None),
        ),
    ]
