# Generated by Django 4.2 on 2024-03-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_cointypemodel_usermodel_coin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='coin_status',
            field=models.BooleanField(default=False),
        ),
    ]
