# Generated by Django 4.2 on 2024-03-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_usermodel_coin_status_cointypemodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cointypemodel',
            name='status',
        ),
        migrations.AddField(
            model_name='coinmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
