# Generated by Django 4.2 on 2024-03-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_cointypemodel_status_coinmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinmodel',
            name='status',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='coin_status',
            field=models.BooleanField(default=False),
        ),
    ]
