# Generated by Django 4.2 on 2024-03-29 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_networkmodel_coinmodel_coin_type_qrmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinmodel',
            old_name='coin_type',
            new_name='cointype',
        ),
        migrations.RenameField(
            model_name='coinmodel',
            old_name='network_type',
            new_name='networktype',
        ),
        migrations.RenameField(
            model_name='depositmodel',
            old_name='coin_type',
            new_name='cointype',
        ),
        migrations.RenameField(
            model_name='depositmodel',
            old_name='network_type',
            new_name='networktype',
        ),
        migrations.RenameField(
            model_name='qrmodel',
            old_name='link_address',
            new_name='linkaddress',
        ),
        migrations.RenameField(
            model_name='qrmodel',
            old_name='link_name',
            new_name='linkname',
        ),
    ]
