# Generated by Django 4.2 on 2024-03-29 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_coin_type_coinmodel_cointype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coinmodel',
            old_name='cointype',
            new_name='coin_type',
        ),
        migrations.RenameField(
            model_name='coinmodel',
            old_name='networktype',
            new_name='network_type',
        ),
        migrations.RenameField(
            model_name='depositmodel',
            old_name='cointype',
            new_name='coin_type',
        ),
        migrations.RenameField(
            model_name='depositmodel',
            old_name='networktype',
            new_name='network_type',
        ),
        migrations.RenameField(
            model_name='qrmodel',
            old_name='linkaddress',
            new_name='link_address',
        ),
        migrations.RenameField(
            model_name='qrmodel',
            old_name='linkname',
            new_name='link_name',
        ),
    ]
