# Generated by Django 4.2 on 2024-03-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_cointype_coinmodel_coin_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
