# Generated by Django 4.2 on 2024-04-01 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_withdrawmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroModel',
        ),
    ]
