# Generated by Django 4.2 on 2024-04-01 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_heromodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRModel',
        ),
        migrations.RemoveField(
            model_name='coinmodel',
            name='network_type',
        ),
        migrations.RemoveField(
            model_name='depositmodel',
            name='network_type',
        ),
        migrations.RemoveField(
            model_name='withdrawmodel',
            name='network_type',
        ),
        migrations.DeleteModel(
            name='NetworkModel',
        ),
    ]
